[project]
name = "robotvision2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.5.0",
    "numpy==2.1.1",
    "opencv-contrib-python==4.12.0.88",  # or 4.11.0.86
    "opencv-python==4.12.0.88",  # or 4.11.0.86
]
